version: '3.7'

# Define services
services:
  # Payment Service
  payment-server:
    # Configuration for building the docker image for the backend service
    image: 'payment-service:1.0.0'
    build:
      context: payment-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
  
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    image: 'distance-server:1.0.0'
    build:
      context: distance
      dockerfile: Dockerfile
    ports:
      - "8086:8086" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on: 
      - db # This service depends on mysql. Start that first.
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/transportationenrollment
      - SPRING_DATASOURCE_USERNAME=$pg_user
      - SPRING_DATASOURCE_PASSWORD=$pg_pwd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # Frontend Service 
  app-client:
    image: 'distance-ui:1.0.0'
    build:
      context: distance-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80" # Map the exposed port 80 on the container to port 9090 on the host machine
      - "443:443"
    restart: always
    volumes:
     - /etc/ngnix/ssl:/etc/ngnix/ssl
    depends_on:
      - app-server

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=$pg_user
      - POSTGRES_PASSWORD=$pg_pwd
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
